services:
  tasksapp:
    image: tasksapp
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ConnectionStrings__RenderConnection=Server=dpg-cq4k12o8fa8c73fqpheg-a.oregon-postgres.render.com;Port=5432;Database=todolist_db_24d1;User Id=todolist_db_24d1_user;Password=b732bDRVRWK8VCG7YfdgUUxG0fg6JAr3;SSL Mode=Require;Trust Server Certificate=true;
    ports:
      - "8080:8080"