services:
  tasksapp:
    image: tasksapp
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
       
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: todolist
      POSTGRES_USER: todolist
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"